### ISSUE TITLE
[PACKAGE] Go library for writing commands

### ISSUE THREAD

**Issue by Aleph0x** [sisyphean-cabal/HATE#1]
Lykkin, [12/26/22 9:05 AM]
You are gonna need to make a bunch of commands

Lykkin, [12/26/22 9:06 AM]
Find a lib to help write commands

Lykkin, [12/26/22 9:06 AM]
Not just cli

Lykkin, [12/26/22 9:06 AM]
But we want separate cmd files for each operation

**Comment by lykkin** [comment]
we can use https://github.com/jessevdk/go-flags to handle parsing out the cli stuff, which should be a fine place to start. we should be conscious of adding other protocols to interact with the system though. e.g. it would be cool to expose an http interface or grpc interace to control it.

**Comment by Aleph0x** [comment]
https://github.com/mitchellh/cli
This is a library for implementing CLI's in Go. It powers Packer, Consul, Vault, Terraform, and Nomad.
Supports sub-command based CLIs: `cli foo`, `cli bar`
Supports nested subcommands `cli foo bar`
Automated help flag recognition `-h` `--help`

https://grpc.io/docs/languages/go/quickstart/
Protocol wise I'm down with gRPC. Also GoLang already has an official package for protocol buffers https://pkg.go.dev/google.golang.org/protobuf so it just seems like the right thing to use.

**Comment by Aleph0x** [comment]
> we can use https://github.com/jessevdk/go-flags to handle parsing out the cli stuff, which should be a fine place to start. we should be conscious of adding other protocols to interact with the system though. e.g. it would be cool to expose an http interface or grpc interace to control it.

Actually, go-flags seems more flushed out and has a lot more in the way of working with the library. Their docs seem pretty good as well. Let's roll with that.
